### ISSUE TITLE
fix next-translate 📖 

### ISSUE THREAD

**Issue by 3lLobo** [AERX-dev/aerx-frontend-near#2]
Next translate is still not working.
Compare to the old repo and see if you can make it work again without importing unnecessary code.

**Comment by peteruche21** [comment]
the issue with next translate is from the next config... you didn't use it in the module exports. [reference](https://dev.to/evalcraciun/translate-your-next-js-project-with-next-translate-2aa5)

**Comment by peteruche21** [comment]
fixed!
