### ISSUE TITLE
Profile SideCard 🎴 

### ISSUE THREAD

**Issue by 3lLobo** [AERX-dev/aerx-frontend-near#47]
Fix he overflow of the Profile SideCard in a graceful manner ✨

**Comment by nitin094-hub** [comment]
I would like to do it.

**Comment by nitin094-hub** [comment]
Could you plz elaborate on the problem a bit?

**Comment by 3lLobo** [comment]
Sure, let's see what you got 😉 
Follow the contribution guide and open a PR.

The issue:
The card with the profile should have a max-height of the screen height. Fix the overflow in a nice way.

**Comment by nitin094-hub** [comment]
![Screenshot (87)](https://user-images.githubusercontent.com/73329655/161733071-96ee195b-aa12-4e86-92a8-554f6859d624.png)

You mean this profile card should take the whole page, right?
